//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public long inn { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public bool salesman { get; set; }
        public bool buyer { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
