//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public Production()
        {
            this.ProductionMaterial = new HashSet<ProductionMaterial>();
        }
    
        public int id { get; set; }
        public decimal quantity { get; set; }
        public System.DateTime date { get; set; }
        public int product_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductionMaterial> ProductionMaterial { get; set; }
    }
}
