//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderItem = new HashSet<OrderItem>();
            this.Production = new HashSet<Production>();
            this.Specification = new HashSet<Specification>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<Production> Production { get; set; }
        public virtual ICollection<Specification> Specification { get; set; }
    }
}
