//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationItem
    {
        public int id { get; set; }
        public int material_id { get; set; }
        public decimal quantity { get; set; }
        public int specification_id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
