//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public Specification()
        {
            this.SpecificationItem = new HashSet<SpecificationItem>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int product_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<SpecificationItem> SpecificationItem { get; set; }
    }
}
